### ISSUE TITLE
nil pointer dereference if endpoint not set

### ISSUE THREAD

**Issue by scross01** [hashicorp/go-oracle-terraform#138]
This SDK issue is observed with the terraform provider when the `endpoint` is not set

https://github.com/terraform-providers/terraform-provider-opc/issues/116

e.g.

```
provider "opc" {
  user = "stephen.cross@oracle.com"
  password = "Pa55_Word"
  identity_domain = "mydomain"
  endpoint = ""
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
2018-03-27T14:24:03.731-0400 [DEBUG] plugin.terraform-provider-opc_v1.1.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x158193a]
2018-03-27T14:24:03.731-0400 [DEBUG] plugin.terraform-provider-opc_v1.1.0_x4: 
2018-03-27T14:24:03.731-0400 [DEBUG] plugin.terraform-provider-opc_v1.1.0_x4: goroutine 45 [running]:
2018-03-27T14:24:03.731-0400 [DEBUG] plugin.terraform-provider-opc_v1.1.0_x4: github.com/terraform-providers/terraform-provider-opc/vendor/github.com/hashicorp/go-oracle-terraform/compute.(*ComputeClient).getUserName(0x0, 0xc4204509c0, 0xc420054000)
2018-03-27T14:24:03.731-0400 [DEBUG] plugin.terraform-provider-opc_v1.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-opc/vendor/github.com/hashicorp/go-oracle-terraform/compute/compute_client.go:84 +0x4a
2018-03-27T14:24:03.731-0400 [DEBUG] plugin.terraform-provider-opc_v1.1.0_x4: github.com/terraform-providers/terraform-provider-opc/vendor/github.com/hashicorp/go-oracle-terraform/compute.(*ComputeClient).getQualifiedName(0x0, 0xc4202fe2a0, 0x5, 0xc4202dd818, 0x1010c58)
2018-03-27T14:24:03.731-0400 [DEBUG] plugin.terraform-provider-opc_v1.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-opc/vendor/github.com/hashicorp/go-oracle-terraform/compute/compute_client.go:106 +0x8b
```

**Comment by scross01** [comment]
Issues actually in the provider implementation trying to calling the `getUserName` SDK method with an uninitialized (nil) client.  Closing this issue and will reverting back to the provider for the fix.
